<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace SolidInvoice\ElectronicInvoicingBundle\Provider;

use Brick\Math\BigInteger;
use DateTimeImmutable;
use SolidInvoice\ElectronicInvoicingBundle\Entity\ElectronicInvoiceSubmission;
use SolidInvoice\ElectronicInvoicingBundle\Enum\ElectronicInvoiceProcessingStatus;
use SolidInvoice\ElectronicInvoicingBundle\Form\Type\Provider\TestProviderConfigType;
use SolidInvoice\InvoiceBundle\Entity\Invoice;
use Symfony\Component\DependencyInjection\Attribute\AsTaggedItem;
use Symfony\Component\Uid\Uuid;

/**
 * Simulates a successful (or, on demand, failed) submission without ever
 * calling out to a real platform. Exists to prove the provider pipeline
 * (settings, marketplace UI, dispatch, submission history) end-to-end
 * before a real platform (Chorus Pro, a PDP, ...) is implemented.
 */
#[AsTaggedItem('test_provider')]
final class TestProvider implements ElectronicInvoiceProviderInterface, ElectronicInvoiceReceiverInterface
{
    public static function getName(): string
    {
        return 'test_provider';
    }

    public function getForm(): string
    {
        return TestProviderConfigType::class;
    }

    /**
     * @param array{reference_prefix?: string, simulate_failure?: bool} $config
     */
    public function send(Invoice $invoice, array $config): ElectronicInvoiceSubmissionResult
    {
        if ($config['simulate_failure'] ?? false) {
            return ElectronicInvoiceSubmissionResult::failure('einvoicing.provider.test.simulated_failure');
        }

        $prefix = $config['reference_prefix'] ?? 'TEST';

        return ElectronicInvoiceSubmissionResult::success(
            sprintf('%s-%s', $prefix, Uuid::v4()),
        );
    }

    /**
     * No external platform is ever actually contacted, so there is no
     * asynchronous processing to reflect — a successful submission just
     * stays Pending indefinitely, and a failed one is immediately Rejected.
     */
    public function resolveProcessingStatus(ElectronicInvoiceSubmission $submission): ElectronicInvoiceProcessingStatus
    {
        return $submission->isSuccess() ? ElectronicInvoiceProcessingStatus::Pending : ElectronicInvoiceProcessingStatus::Rejected;
    }

    /**
     * Reports exactly one simulated incoming invoice the first time it's polled
     * ($afterExternalReference === null, i.e. nothing imported yet) and nothing
     * on every poll after — the same "nothing new" behaviour a real inbox
     * settles into, without ever calling out to a real platform.
     */
    public function fetchIncoming(array $config, ?string $afterExternalReference): array
    {
        if ($afterExternalReference !== null) {
            return [];
        }

        return [
            new ReceivedElectronicInvoiceData(
                externalReference: 'test-incoming-' . Uuid::v4(),
                invoiceNumber: 'DEMO-0001',
                sellerName: 'Demo Supplier Inc.',
                sellerIdentifier: '000000001',
                issueDate: new DateTimeImmutable('-3 days'),
                totalAmount: BigInteger::of(12000),
                currencyCode: 'EUR',
                statusCode: null,
            ),
        ];
    }

    public function downloadIncomingDocument(array $config, string $externalReference): DownloadedElectronicInvoiceDocument
    {
        return new DownloadedElectronicInvoiceDocument(
            "Simulated received invoice document for {$externalReference}.\nGenerated by the Test Provider — no real electronic-invoicing platform was contacted.",
            'text/plain',
            'txt',
        );
    }
}
