apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "augias.fullname" . }}
  labels:
    {{- include "augias.labels" . | nindent 4 }}
data:
  AUGIAS_ENV: "prod"
  AUGIAS_DEBUG: "0"
  AUGIAS_DOCKER: "true"
  AUGIAS_CONFIG_DIR: "/etc/augias"
  AUGIAS_LOCALE: {{ .Values.app.locale | quote }}
  AUGIAS_ALLOW_REGISTRATION: {{ .Values.app.allowRegistration | toString | quote }}
  {{- if .Values.app.url }}
  AUGIAS_APPLICATION_URL: {{ .Values.app.url | quote }}
  {{- end }}
  AUGIAS_MAILER_SENDER: {{ .Values.mailer.sender | quote }}
  {{- if .Values.sentry.enabled }}
  AUGIAS_SENTRY_RELEASE: {{ default .Chart.AppVersion .Values.image.tag | quote }}
  AUGIAS_SENTRY_SEND_DEFAULT_PII: "false"
  {{- end }}
  {{- if .Values.app.workerMode }}
  FRANKENPHP_WORKER_MODE: "1"
  {{- end }}
