<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace SolidInvoice\NotificationBundle\Form\Type\Transport;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @codeCoverageIgnore
 * @extends AbstractType<array{login: mixed, api_key: mixed, phone: mixed}>
 */
final class FreeMobileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'login',
            null,
            [
                'label' => 'form.field.login',
                'constraints' => new NotBlank(groups: ['freemobile']),
            ]
        );

        $builder->add(
            'api_key',
            null,
            [
                'label' => 'form.field.api_key',
                'constraints' => new NotBlank(groups: ['freemobile']),
            ]
        );

        $builder->add(
            'phone',
            null,
            [
                'label' => 'form.field.phone',
                'constraints' => new NotBlank(groups: ['freemobile']),
            ]
        );
    }
}
