<?php

declare(strict_types=1);

/*
 * This file is part of Augias project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace Augias\NotificationBundle\Form\Type\Transport;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @codeCoverageIgnore
 * @extends AbstractType<array{token: mixed, user_id: mixed}>
 */
final class LinkedInType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'token',
            null,
            [
                'label' => 'form.field.token',
                'constraints' => new NotBlank(groups: ['linkedin']),
            ]
        );

        $builder->add(
            'user_id',
            null,
            [
                'label' => 'form.field.user_id',
                'constraints' => new NotBlank(groups: ['linkedin']),
            ]
        );
    }
}
