<?php

declare(strict_types=1);

/*
 * This file is part of SolidInvoice project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace SolidInvoice\NotificationBundle\Form\Type\Transport;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @codeCoverageIgnore
 * @extends AbstractType<array{access_token: mixed, host: mixed, path: mixed, channel: mixed}>
 */
final class MattermostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'access_token',
            null,
            [
                'label' => 'form.field.access_token',
                'constraints' => new NotBlank(groups: ['mattermost']),
            ]
        );

        $builder->add(
            'host',
            null,
            [
                'label' => 'form.field.host',
                'constraints' => new NotBlank(groups: ['mattermost']),
            ]
        );

        $builder->add(
            'path',
            null,
            [
                'label' => 'form.field.path',
                'constraints' => new NotBlank(groups: ['mattermost']),
            ]
        );

        $builder->add(
            'channel',
            null,
            [
                'label' => 'form.field.channel',
                'constraints' => new NotBlank(groups: ['mattermost']),
            ]
        );
    }
}
