<?php

declare(strict_types=1);

/*
 * This file is part of Augias project.
 *
 * (c) Pierre du Plessis <open-source@solidworx.co>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

// !! This file is autogenerated. Do not edit. !!

namespace Augias\NotificationBundle\Form\Type\Transport;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @codeCoverageIgnore
 * @extends AbstractType<array{uid: mixed, api_key: mixed, from: mixed, test_mode: mixed}>
 */
final class SmsBiurasType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder->add(
            'uid',
            null,
            [
                'label' => 'form.field.uid',
                'constraints' => new NotBlank(groups: ['smsbiuras']),
            ]
        );

        $builder->add(
            'api_key',
            null,
            [
                'label' => 'form.field.api_key',
                'constraints' => new NotBlank(groups: ['smsbiuras']),
            ]
        );

        $builder->add(
            'from',
            null,
            [
                'label' => 'form.field.from',
                'constraints' => new NotBlank(groups: ['smsbiuras']),
            ]
        );

        $builder->add(
            'test_mode',
            null,
            [
                'label' => 'form.field.test_mode',
                'constraints' => new NotBlank(groups: ['smsbiuras']),
            ]
        );
    }
}
