apiVersion: v2
name: augias
description: Billing and invoicing application for small businesses
type: application
version: 1.0.0
appVersion: "3.0.0"

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/maintainers: |
    - name: Pierre du Plessis
      email: open-source@solidworx.co
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/herc-si/SolidInvoice

dependencies:
  - name: mysql
    version: "11.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled

  - name: postgresql
    version: "15.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

  - name: redis
    version: "19.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled

  - name: meilisearch
    version: "0.x.x"
    repository: https://meilisearch.github.io/meilisearch-kubernetes
    condition: meilisearch.enabled
